- hosts: default
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Prometheus user exists
      user:
        name: prometheus
    - name: Node exporter dir exists
      file:
        path: /home/prometheus/node_exporter
        state: directory
    - name: Node exporter into /home/prometheus/node_exporter extracted
      unarchive:
        remote_src: yes
        src: https://github.com/prometheus/node_exporter/releases/download/v0.14.0/node_exporter-0.14.0.linux-amd64.tar.gz
        dest: /home/prometheus/node_exporter
        creates: /home/prometheus/node_exporter/node_exporter-0.14.0.linux-amd64/node_exporter
    - name: Unit file for node exporter copied
      copy:
        src: node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
    - name: Node exporter started
      systemd:
        name: node_exporter
        daemon_reload: yes
        enabled: yes
        state: started
    - name: Prometheus dir exists
      file:
        path: /home/prometheus/prometheus
        state: directory
    - name: Prometheus into /home/prometheus/prometheus extracted
      unarchive:
        remote_src: yes
        src: https://github.com/prometheus/prometheus/releases/download/v1.8.1/prometheus-1.8.1.linux-amd64.tar.gz
        dest: /home/prometheus/prometheus
        creates: /home/prometheus/prometheus/prometheus-1.8.1.linux-amd64/prometheus
    - name: Prometheus data dir exists
      file:
        path: /home/prometheus/prometheus/prometheus-1.8.1.linux-amd64/data
        state: directory
        owner: prometheus
        group: prometheus
    - name: Unit file for prometheus copied
      copy:
        src: prometheus.service
        dest: /etc/systemd/system/prometheus.service
    - name: Configuration file for prometheus copied
      copy:
        src: prometheus.yml
        dest: /home/prometheus/prometheus/prometheus-1.8.1.linux-amd64/prometheus.yml
    - name: Prometheus started
      systemd:
        name: prometheus
        daemon_reload: yes
        enabled: yes
        state: started
    - name: Grafana installed
      yum:
        name: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-4.6.1-1.x86_64.rpm
        state: present
    - name: Grafana started
      systemd:
        name: grafana-server
        daemon_reload: yes
        enabled: yes
        state: started
    - name: Unit file for dummy service copied
      copy:
        src: dummy.service
        dest: "/etc/systemd/system/dummy{{ item }}.service"
      with_sequence: start=1 end=10
    - name: Dummy service started
      systemd:
        name: "dummy{{ item }}"
        daemon_reload: yes
        enabled: yes
        state: started
      with_sequence: start=1 end=10